In [ ]:
# config.py, yamls - wham_api 
#from wham_api import WHAM_API
#wham_model = WHAM_API()

In [ ]:
import yt_dlp
url = "https://www.tiktok.com/@so._.ya_/video/7493762554888539400?q=%EC%B6%A4&t=1744863380603"
ydl_opts = {'outtmpl': 'tiktok_video.mp4'}

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    ydl.download([url])

In [ ]:
#input_video_path = 'tiktok_video.mp4'
#results, tracking_results, slam_results = wham_model(input_video_path)

In [ ]:
#results[0]['poses_body'].shape

## 포즈 추출

In [2]:
!python demo.py --video tiktok_video.mp4 --run_smplify --save_pkl # yamlize

apex is not installed
apex is not installed
apex is not installed
/home/epikskool/miniconda3/envs/detr/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:27: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
2025-04-22 17:01:49.620 | INFO     | __main__:<module>:210 - GPU name -> NVIDIA GeForce RTX 4090
2025-04-22 17:01:49.620 | INFO     | __main__:<module>:211 - GPU feat -> _CudaDeviceProperties(name='NVIDIA GeForce RTX 4090', major=8, minor=9, total_memory=24563MB, multi_processor_count=128)
2025-04-22 17:01:50.002 | INFO     | lib.models:build_network:36 - => loaded checkpoint 'checkpoints/wham_vit_bedlam_w_3dpw.pth.tar' 
Use load_from_local loader
Load backbone weight: /home/epikskool/workspace/workdir/WHAM/checkpoints/hmr2a.ckpt
/home/epikskool/workspace/workdir/WHAM/lib/models/preproc/bac

## 포즈 캡처 npz 파일 보기

In [5]:
import numpy as np
npyfile = np.load('output/demo/tiktok_video/tiktok_video.mp4_output.npz', allow_pickle=True)

In [6]:
type(npyfile)

numpy.lib.npyio.NpzFile

In [7]:
npyfile.files

['arr_0']

In [8]:
arr = npyfile['arr_0']
data = arr.item()

In [9]:
data[0].keys()

dict_keys(['pose', 'trans', 'betas', 'frame_ids'])

In [10]:
data[0]['pose'].shape

(1028, 72)

In [11]:
data[0]['pose']

array([[ 3.10430670e+00,  2.58179065e-02,  8.68467521e-03, ...,
        -4.41313498e-02,  4.79955226e-02,  1.34233698e-01],
       [ 3.09337044e+00,  2.43225545e-02,  1.05235921e-02, ...,
        -1.61161590e-02,  5.71359619e-02,  1.04742683e-01],
       [ 3.09216142e+00,  2.26763859e-02,  9.67452489e-03, ...,
        -2.22156700e-02,  5.36183491e-02,  1.04706667e-01],
       ...,
       [ 3.00790381e+00,  2.56031826e-02, -2.80887093e-02, ...,
        -1.19120367e-01,  2.91516935e-03,  2.23170727e-01],
       [ 3.00983047e+00,  2.21225005e-02, -2.87950635e-02, ...,
        -1.19313546e-01,  2.79690675e-03,  2.23183319e-01],
       [ 3.00785923e+00,  2.37666853e-02, -2.87496857e-02, ...,
        -1.19245097e-01,  2.73671164e-03,  2.23117843e-01]], dtype=float32)

In [12]:
data[0]['trans'].shape

(1028, 3)

In [13]:
data[0]['trans']

array([[-3.1549763e-03,  1.0174209e-01,  2.9434803e+00],
       [-4.4638664e-03,  9.7630523e-02,  2.9496882e+00],
       [-3.6835670e-03,  9.4866008e-02,  2.9515071e+00],
       ...,
       [-2.0068111e-03,  6.1925601e-02,  2.9616959e+00],
       [ 4.9680565e-04,  6.1555102e-02,  2.9625630e+00],
       [-5.5578211e-04,  6.2395584e-02,  2.9601619e+00]], dtype=float32)

In [16]:
data[0]['betas'].shape

(1028, 10)

In [17]:
data[0]['betas']

array([[ 0.05011236,  1.3054744 ,  0.54989946, ...,  0.83006734,
         0.41350502,  0.3950795 ],
       [ 0.00448683,  1.3873546 ,  0.7589375 , ...,  1.1162362 ,
         0.58239925,  0.6346429 ],
       [-0.02101943,  1.3960319 ,  0.82615495, ...,  1.0651929 ,
         0.6264393 ,  0.6493278 ],
       ...,
       [-0.11226956,  1.5354526 , -0.44505608, ...,  0.80958915,
         1.4308169 , -0.40353408],
       [-0.11057475,  1.5349349 , -0.4453251 , ...,  0.8126358 ,
         1.4279759 , -0.40228727],
       [-0.10938658,  1.5348129 , -0.44560805, ...,  0.8175827 ,
         1.4252038 , -0.40021837]], dtype=float32)