In [ ]:
from wham_api import WHAM_API
wham_model = WHAM_API()

apex is not installed
apex is not installed
apex is not installed


/home/epikskool/miniconda3/envs/detr/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:27: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
2025-04-21 15:14:25.546 | INFO     | lib.models:build_network:36 - => loaded checkpoint 'checkpoints/wham_vit_bedlam_w_3dpw.pth.tar' 


Use load_from_local loader
Load backbone weight: /home/epikskool/workspace/workdir/WHAM/checkpoints/hmr2a.ckpt


SMPL Parameters:


In [2]:
input_video_path = 'tiktok_video.mp4'
results, tracking_results, slam_results = wham_model(input_video_path)

/home/epikskool/workspace/workdir/WHAM/lib/models/preproc/backbone/smpl_head.py:25: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /opt/conda/conda-bld/pytorch_1716905969824/work/aten/src/ATen/native/Cross.cpp:62.)
  b3 = torch.cross(b1, b2)


In [8]:
results

defaultdict(dict,
            {0: {'poses_body': array([[[[    0.99732,     0.07067,   -0.018991],
                       [   -0.07056,     0.99749,   0.0063937],
                       [   0.019395,  -0.0050366,      0.9998]],
              
                      [[    0.99647,   -0.083696,  -0.0067262],
                       [   0.083916,     0.98992,     0.11408],
                       [ -0.0028901,    -0.11425,     0.99345]],
              
                      [[    0.99963,  -0.0049711,    -0.02688],
                       [  0.0018584,     0.99341,    -0.11461],
                       [   0.027273,     0.11451,     0.99305]],
              
                      ...,
              
                      [[    0.97627,     0.16859,     0.13595],
                       [   -0.19345,     0.96104,     0.19744],
                       [  -0.097365,    -0.21905,     0.97084]],
              
                      [[    0.99088,     0.12961,   -0.036735],
                       [   

In [5]:
import numpy as np
npyfile = np.load('output/demo/tiktok_video/tiktok_video.mp4_output.npz', allow_pickle=True)

In [6]:
type(npyfile)

numpy.lib.npyio.NpzFile

In [7]:
npyfile.files

['arr_0']

In [ ]:
arr = npyfile['arr_0']
data = arr.item()

In [23]:
data[0].keys()

dict_keys(['pose', 'trans', 'pose_world', 'trans_world', 'betas', 'verts', 'frame_ids'])

In [25]:
data[0]['pose'].shape

(1028, 72)

In [32]:
data[0]['pose']

array([[ 3.10430670e+00,  2.58179065e-02,  8.68467521e-03, ...,
        -4.41313498e-02,  4.79955226e-02,  1.34233698e-01],
       [ 3.09337044e+00,  2.43225545e-02,  1.05235921e-02, ...,
        -1.61161590e-02,  5.71359619e-02,  1.04742683e-01],
       [ 3.09216142e+00,  2.26763859e-02,  9.67452489e-03, ...,
        -2.22156700e-02,  5.36183491e-02,  1.04706667e-01],
       ...,
       [ 3.00790381e+00,  2.56031826e-02, -2.80887093e-02, ...,
        -1.19120367e-01,  2.91516935e-03,  2.23170727e-01],
       [ 3.00983047e+00,  2.21225005e-02, -2.87950635e-02, ...,
        -1.19313546e-01,  2.79690675e-03,  2.23183319e-01],
       [ 3.00785923e+00,  2.37666853e-02, -2.87496857e-02, ...,
        -1.19245097e-01,  2.73671164e-03,  2.23117843e-01]], dtype=float32)

In [26]:
data[0]['trans'].shape

(1028, 3)

In [33]:
data[0]['trans']

array([[-3.1549763e-03,  1.0174209e-01,  2.9434803e+00],
       [-4.4638664e-03,  9.7630523e-02,  2.9496882e+00],
       [-3.6835670e-03,  9.4866008e-02,  2.9515071e+00],
       ...,
       [-2.0068111e-03,  6.1925601e-02,  2.9616959e+00],
       [ 4.9680565e-04,  6.1555102e-02,  2.9625630e+00],
       [-5.5578211e-04,  6.2395584e-02,  2.9601619e+00]], dtype=float32)

In [27]:
data[0]['pose_world'].shape

(1028, 72)

In [34]:
data[0]['pose_world']

array([[-0.00873989, -0.02428084,  0.03904668, ..., -0.04413135,
         0.04799552,  0.1342337 ],
       [-0.00710643, -0.01194703,  0.03784791, ..., -0.01611616,
         0.05713596,  0.10474268],
       [-0.00610429, -0.00110917,  0.03762678, ..., -0.02221567,
         0.05361835,  0.10470667],
       ...,
       [-0.13060938, -0.1451204 , -0.0374909 , ..., -0.11912037,
         0.00291517,  0.22317073],
       [-0.1300039 , -0.14052989, -0.03673577, ..., -0.11931355,
         0.00279691,  0.22318332],
       [-0.12944983, -0.13887677, -0.03629419, ..., -0.1192451 ,
         0.00273671,  0.22311784]], dtype=float32)

In [28]:
data[0]['trans_world'].shape

(1028, 3)

In [35]:
data[0]['trans_world']

array([[ 0.00035708,  0.00027661,  0.00147601],
       [ 0.00013879,  0.00115723, -0.00107538],
       [ 0.00162879,  0.0004822 ,  0.00013783],
       ...,
       [ 0.020224  , -0.10343221,  0.09796742],
       [ 0.02067834, -0.10347527,  0.09917352],
       [ 0.01998537, -0.10344414,  0.09932565]], dtype=float32)

In [29]:
data[0]['betas'].shape

(1028, 10)

In [36]:
data[0]['betas']

array([[ 0.05011236,  1.3054744 ,  0.54989946, ...,  0.83006734,
         0.41350502,  0.3950795 ],
       [ 0.00448683,  1.3873546 ,  0.7589375 , ...,  1.1162362 ,
         0.58239925,  0.6346429 ],
       [-0.02101943,  1.3960319 ,  0.82615495, ...,  1.0651929 ,
         0.6264393 ,  0.6493278 ],
       ...,
       [-0.11226956,  1.5354526 , -0.44505608, ...,  0.80958915,
         1.4308169 , -0.40353408],
       [-0.11057475,  1.5349349 , -0.4453251 , ...,  0.8126358 ,
         1.4279759 , -0.40228727],
       [-0.10938658,  1.5348129 , -0.44560805, ...,  0.8175827 ,
         1.4252038 , -0.40021837]], dtype=float32)

In [30]:
data[0]['verts'].shape

(1028, 6890, 3)

In [37]:
data[0]['verts']

array([[[ 0.10109337, -0.8215879 ,  2.8593767 ],
        [ 0.09375943, -0.8091383 ,  2.8525677 ],
        [ 0.10402708, -0.8037684 ,  2.861212  ],
        ...,
        [-0.0221397 , -0.7776518 ,  2.950365  ],
        [-0.0222862 , -0.7794163 ,  2.9488723 ],
        [-0.02516863, -0.7776265 ,  2.9462178 ]],

       [[ 0.10466614, -0.8284809 ,  2.868008  ],
        [ 0.09725356, -0.8161319 ,  2.8610234 ],
        [ 0.10730888, -0.81058997,  2.869707  ],
        ...,
        [-0.01876287, -0.7847609 ,  2.957955  ],
        [-0.01889466, -0.7865309 ,  2.9564764 ],
        [-0.02178026, -0.784821  ,  2.9538124 ]],

       [[ 0.10207643, -0.8311205 ,  2.8700044 ],
        [ 0.09470311, -0.8186982 ,  2.8630264 ],
        [ 0.10479423, -0.81321275,  2.8717144 ],
        ...,
        [-0.0207044 , -0.7868397 ,  2.9603195 ],
        [-0.02085273, -0.78860503,  2.9588413 ],
        [-0.02373741, -0.78688014,  2.9561875 ]],

       ...,

       [[ 0.05205362, -0.77223754,  2.8922532 ],
        [ 0